import Head from "next/head";
import { Box } from "@chakra-ui/react";
import Layout from "@/components/Layout";
import dynamic from "next/dynamic";

const Dashboard = dynamic(
  () => import("@/modules/dashboard/sections/Dashboard"),
  {
    loading: () => null,
    ssr: true,
  }
);

export const DashboardMainPage = () => {
  return (
    <>
      <Head>
        <title>ByteTrail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Dashboard />
      </Layout>
    </>
  );
};

export default DashboardMainPage;
